# Generated by Django 5.1 on 2024-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location_in', models.CharField(max_length=255)),
                ('location_out', models.CharField(max_length=255)),
                ('in_time', models.TimeField()),
                ('range_12pm_user', models.CharField(max_length=255)),
                ('range_3pm_user', models.CharField(max_length=255)),
                ('out_time', models.TimeField()),
                ('stay_in_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
